CREATE TABLE catalog (
    catalog_id INTEGER PRIMARY KEY,
    sku TEXT,
    name TEXT,
    inventory INTEGER,
    potion_type INTEGER[],
    price INTEGER
);

create table
  public.catalog (
    catalog_id bigint generated by default as identity not null,
    sku text null,
    inventory integer null,
    potion_type integer[] null,
    price integer null default 0,
    name text null,
    constraint Catalog_pkey primary key (catalog_id)
  ) tablespace pg_default;

CREATE TABLE cart_items (
    cart_id INTEGER PRIMARY KEY,
    catalog_id INTEGER FOREIGN KEY,
    quantity INTEGER
)

create table
  public.cart_items (
    cart_id bigint generated by default as identity not null,
    quantity integer not null default 0,
    catalog_id bigint not null,
    constraint cart_items_pkey primary key (cart_id),
    constraint Cart_catalog_id_key unique (catalog_id)
  ) tablespace pg_default;

create table
  public.global_inventory (
    id bigint generated by default as identity not null,
    gold integer null,
    red_ml integer null default 0,
    green_ml integer null default 0,
    blue_ml integer null default 0,
    dark_ml integer null default 0,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart (
    id bigint generated by default as identity not null,
    customer_name text null,
    character_class text null,
    level integer null,
    constraint Cart Customer_pkey primary key (id)
  ) tablespace pg_default;